### PR TITLE
Adds fields demo notebook

### PR DESCRIPTION
**Pull request by navidcy**
This is an attempt to add a notebook demonstrating some functionality using custom defined types for fields.

### CODE REVIEW

**Comment by navidcy** [comment]
@glwagner, could we chat a bit about [this notebook](https://nbviewer.jupyter.org/github/dhruvbhagtani/ToyModel.jl/blob/a53cd5b37c248412d33cdc0f55e8974b6dc2cd51/using_fields.ipynb)? I'm not sure why the last part does not reduce allocations...

**Comment by glwagner** [comment]
Yes, happy to chat! You shouldn't need in-place functions like that for single-index operations. I'm not sure which code to compare to what, but if we talk I can try to help.

**Comment by dhruvbhagtani** [comment]
@glwagner thanks for your help! I'll be delighted to join too.

From my brief reading on @inbounds, we would've expected the same number and size of allocations, because all it does is skip the bounds checking (please correct me if I'm wrong). However, what I don't quite understand is the fact that ∂() function allocates some memory each time, even though we don't have any temporary arrays.

**Comment by navidcy** [comment]
@glwagner, I was mostly referring to `@btime ∂!(∂u, u)` vs `@btime ∂_better!(∂u, u)`

**Comment by navidcy** [comment]
> Yes, happy to chat! You shouldn't need in-place functions like that for single-index operations. I'm not sure which code to compare to what, but if we talk I can try to help.

Oh I see, you are arguing that inlace for single index operations doesn't bring any advantage?

**Comment by glwagner** [comment]
Right, we might as well write 

```julia
@inbounds ∂u[i] = ∂(i, u)
```

by the way putting the index first allows the functions to be composed since you can write things like


```julia
∂(i, f::Function, args...) = (f(i, args...) - f(i-1, args...)) / dx
```

**Comment by navidcy** [comment]
@dhruvbhagtani I removed the second optimised version as it was not making it faster.

Although the field abstraction brings up some speedup here the main advantage of it is that:
- it makes the code cleaner
- allows for much generalisation of various functions overloading based on the parameter(s) of the field. For example, here I wrote two methods for `∂` based on whether the `L`ocation parameter of the field is `Cell` or `Face`:
  ```juli
  ∂(i, f::Field{<:Cell}) = δᶠ(i, f.data) / f.grid.dx
  ∂(i, f::Field{<:Face}) = δᶜ(i, f.data) / f.grid.dx
  ```

**Comment by dhruvbhagtani** [comment]
The simpler field looks much better.

**Review by dhruvbhagtani — APPROVED** [review]

**Pull request merged**
