### PR TITLE
Runge Kutta 4th order on 1D SWE

### PR DESCRIPTION
**Pull request by dhruvbhagtani**
This solves 1D SWE using 4th order Runge Kutta scheme. It is optimised, but could be done more, as the RK4 function has 20 allocations.

### CODE REVIEW

**Comment by navidcy** [comment]
@dhruvbhagtani, I see a lot of notebooks were updated. Do I need to have a look only in the 1D SWE?

I also suggest you delete all `Grids` files from this repo to clean it up.

**Comment by dhruvbhagtani** [comment]
Yes, the only relevant file is [this](https://github.com/dhruvbhagtani/ToyModel.jl/blob/db/RK4/1D_SWE/RK4_Conservative.ipynb).

**Comment by navidcy** [comment]
OK, regarding the 1D SWE notebook:

Looks like you implemented the RK4 OK.

I can't see any mistakes but I didn't spend time looking tbh.
But how will you be sure? Yes, you plotted something and it's not blowing up. But is this 4th order accuracy? How does it compare to the Euler one? There needs to be some sort of quantitative assessment .

Another remark is that the implementation is a bit clumsy. For example, have a look at

```julia
function RK4(dt, U, h, k1U, k2U, k3U, k4U, k1h, k2h, k3h, k4h, U_right, h_right, U_avg, h_avg, adv, dUdx, dhdx, flow_sign, grid, g)
   
   ...

end
```
I can't even easily count the number of arguments that this function have...

**Comment by navidcy** [comment]
> ```julia
> function RK4(dt, U, h, k1U, k2U, k3U, k4U, k1h, k2h, k3h, k4h, U_right, h_right, U_avg, h_avg, adv, dUdx, dhdx, flow_sign, grid, g)
>    
>    ...
> 
> end
> ```
> 
> I can't even easily count the number of arguments that this function have...

And when we go to 2D there will be more args.

**Comment by navidcy** [comment]
On second thought perhaps making the code elegant at this point is not crucial. But we should check somehow whether this scheme made a difference. We can chat about ideas how to do that (either by zoom or here)?

**Comment by dhruvbhagtani** [comment]
Qualitatively, I know that this scheme made a difference, because there were wiggles following the waves in the Euler explicit case, which do come in RK4, but much later. But you're right, some sort of quantitative analysis is required. 

At this stage, I'm not worried about cleaning up the code beyond a certain extent. We can do it once we're sure the code is doing what it's expected to do. Happy to chat on zoom whenever you're free.

**Comment by navidcy** [comment]
Good to know that you've seen qualitative difference from the Euler time-stepping scheme.
Sure let's chat over zoom. I'll ping you either later today or we'll do that at some point tomorrow.

**Comment by dhruvbhagtani** [comment]
Great!

**Review by navidcy — APPROVED** [review]
I approve but I want to remark that I only looked at the 1D SWE RK4 notebook.

It's a bit overwhelming to open PRs with lots of notebooks updated, especially if the updates are unrelated. :)

**Comment by dhruvbhagtani** [comment]
I apologise for the mess. I am still learning all this, so by mistake, I mixed up changes of two pull requests together.

**Pull request merged**
