### PR TITLE
2D SWE using Euler explicit scheme

### PR DESCRIPTION
**Pull request by dhruvbhagtani**
Plotting can be cleaner, and more descriptive.

### CODE REVIEW

**Comment by navidcy** [comment]
oh boy, this is a *huge* PR! :)

**Comment by navidcy** [comment]
One general remark: Let's drop the `grids` from here and use those developed here: https://github.com/ClimateFluidPhysics-ANU/MixedLayerThermoclineDynamics.jl/pull/1

Otherwise we'll. be doing 2 x (N x) the job. :)

**Comment by navidcy** [comment]
@dhruvbhagtani, should we finish ClimateFluidPhysics-ANU/MixedLayerThermoclineDynamics.jl#1 first? Then at least we won't have to double check the grids here.

**Comment by navidcy** [comment]
Btw, the PR contains scripts that seem duplicate, e.g. `Grids/Staggered.jl` and `Staggered/Grids/Staggered.jl`. But I suggest we just work on the finish ClimateFluidPhysics-ANU/MixedLayerThermoclineDynamics.jl#1 and the just use *those* grids and worry no more. :)

**Comment by dhruvbhagtani** [comment]
Haha, yes I changed some small bits to make the code cleaner.
Happy to start with the [MixedLayerThermocline](https://github.com/ClimateFluidPhysics-ANU/MixedLayerThermoclineDynamics.jl/pull/1) but before that, I feel it will be better if we figure out why the 2D SWE is blowing up. A bit of explanation:
The code in this PR works well for about 2-2.5 seconds, and then wiggles start to creep in, which is a bit unusual for staggered grids. What's interesting is that the Python version of the code, which "to my knowledge" is exactly the same, except for the grids generation, is stable always. The grid generation in this PR is (where U is velocity and T is tracer):
U-----T-----U-----T-----U-----T-----U-----T

whereas in the Python code (here's the [link](https://github.com/dhruvbhagtani/toy-model/blob/master/2D_SWE/Conservative_form.ipynb)), it is:
U-----T-----U-----T-----U-----T-----U

Note: In the python notebook linked above - Cell [9] and later are relevant. Also, invoking Cell[5] is necessary, as it prescribes periodic boundary conditions.

The reason it's important to figure it out is that the [MixedLayerThermocline](https://github.com/ClimateFluidPhysics-ANU/MixedLayerThermoclineDynamics.jl/pull/1) uses the same grid as this PR.

**Comment by navidcy** [comment]
FYI: The MixedLayerThermiclineDynamics PR won’t get merged with this grid — don’t worry. I just haven’t commented on that yet because there were even more basic issues (eg the code in the Pr doesn’t work at all).

**Comment by navidcy** [comment]
OK, two remarks:

1. The notebook doesn't work for me. I had to manually activate the environment one level up and also add CircularArrays.jl to that environment.
2. The grids are not correct. Even with the configuration you noted above, when I used `nx=7` and `L=6` I got:
```Julia
grid.xt

6-element Vector{Float64}:
 -2.4545454545454546
 -1.3636363636363638
 -0.2727272727272725
  0.8181818181818179
  1.9090909090909096
  3.0
```
As you see, the last `xt` point is at an interface and **not** at a center. Also,

```Julia
grid.xu

6-element Vector{Float64}:
 -3.0
 -1.9090909090909094
 -0.8181818181818179
  0.2727272727272725
  1.363636363636364
  2.4545454545454546
```
the last `xu` point is in a center, not at an interface..... I believe that this is the source of the issue.

I strongly suggest we construct the grids proper once and for all and then move on from there. We don't need to create the grid every time from scratch. Let's do it once in the `MixedLayerThemorclineDynamics.jl` repo which is continuously tested.

**Comment by navidcy** [comment]
OK, I was wrong... the grids may be correct with the grid structure you pointed above.

**Comment by dhruvbhagtani** [comment]
It's a serious mistake if the code doesn't work and we have to add dependencies. I'll correct it.

**Comment by navidcy** [comment]
Should I still have a look a this or has it been superseded/fixed/dealt with?

**Comment by dhruvbhagtani** [comment]
No, it got merged automatically when I merged the RK4. I'll start a new pull request to make changes.

**Pull request merged**
